### ISSUE TITLE
XMLSyntaxError

### ISSUE THREAD

**Issue by ShunyangLi** [angelosalatino/dblp-parser#2]
I got the following error:
```
  File "dblp.xml", line 284
    <author>Francesco Trov&ograve;</author>
                                 ^
XMLSyntaxError: Entity 'ograve' not defined, line 284, column 31
```
It seems to be an error caused by decoding

**Comment by angelosalatino** [comment]
Hi

this is the first time I am going though this. Have you included the DTD?

I have just run the code on my side, including the dtd and it works fine, as the definiiton of ograve is included in there.

**Comment by ShunyangLi** [comment]
Hi,

I solved this issue by including DTD.  I saw the code had a download function I thought it would automatically download. However, it didn't download automatically, so I downloaded it myself and it worked.

Thanks so much, the code is really helpful.

Best,
Shunyang
